### ISSUE TITLE
Variables in 'sequence-file' are not resolved

### ISSUE THREAD

**Issue by claudiu-cristea** [ec-europa/ssk#273]
My `.opts.yml` file contains something like:

```yaml
upgrade_commands:
  default:
    ...
    - ${my.custom.dir}/custom_script.sh
    ...
```

Where `my.custom.dir` is a configuration defined in `runner.yml.dist`. However, when running `./vendor/bin/run toolkit:run-deploy`, this variable is not resolved.
