### ISSUE TITLE
Allow to run a list of runner.yml configurable tasks after install

### ISSUE THREAD

**Issue by claudiu-cristea** [ec-europa/ssk#277]
Similar to `toolkit:build-dev`, `toolkit:install-clean` and `toolkit:install-clean` should run a list of tasks configurable in `runner.yml.dist` or `runner.yml`.

```yaml
toolkit:
  install:
    clean:
      commands:
        - ./vendor/bin drush pm:enable devel -y
        - ...
    clone:
      commands:
        - echo "Hello World!"
        - ...
```
